apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkouda-server
  namespace: arkouda
spec:
  replicas: {{ .Values.numServers }}
  selector:
    matchLabels:
      app: arkouda-server
  template:
    metadata:
      labels:
        app: arkouda-server
        name: arkouda-server
        #annotations:
        #k8s.v1.cni.cncf.io/networks: host-device-conf
    spec:
      containers:
        - name: arkouda-server
          image: hokiegeek2/udp-arkouda-server:{{ .Values.releaseVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          #command: [ "sh", "/opt/start-arkouda-server.sh" ]
          command: ['/bin/bash', '-c', '--', 'while true; do sleep 600; done;']
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo created pod > /tmp/pod.txt"]
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
          ports:
          - containerPort: {{ .Values.server.port }}
            hostPort: 5555
          - containerPort: 22
            hostPort: 25
          volumeMounts:
          - name: ssl
            mountPath: "/etc/ssl/arkouda"
          - name: ssh
            mountPath: "/home/ubuntu/ssh-keys"
          env:
            - name: MY_IP
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
            - name: GASNET_MASTERIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NUMLOCALES
              value: {{ .Values.server.numLocales | quote}}
            - name: SSH_SERVERS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: AUTHENTICATE
              value: {{ .Values.server.authenticate | quote}} 
            - name: VERBOSE
              value: {{ .Values.server.verbose | quote }}   
            - name: MEMTRACK
              value: {{ .Values.server.memTrack | quote }}
            - name: CERT_FILE
              value: {{ .Values.server.certFile | quote }}
            - name: KEY_FILE
              value: {{ .Values.server.keyFile | quote }}   
            - name: K8S_HOST
              value: {{ .Values.server.k8sHost | quote }}   
            - name: CHPL_RT_NUM_THREADS_PER_LOCALE
              value: {{ .Values.server.threadsPerLocale | quote }}
            - name: GASNET_SUPERNODE_MAXSIZE
              value: '1'  
            - name: NAMESPACE
              value: {{ .Values.external.namespace }}
            - name: EXTERNAL_SERVICE_NAME
              value: {{ .Values.external.externalServiceName }}
            - name: EXTERNAL_SERVICE_PORT
              value: {{ .Values.external.externalServicePort | quote}}
            - name: EXTERNAL_SERVICE_TARGET_PORT
              value: {{ .Values.external.externalServiceTargetPort | quote}}       
      volumes:              
        - name: ssl
          secret:
            secretName: arkouda-server 
        - name: ssh
          secret:
            secretName: arkouda-ssh          
