apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: arkouda-locale
  namespace: arkouda
spec:
  replicas: {{ .Values.server.numLocales }}
  selector:
    matchLabels:
      app: arkouda-locale
  template:
    metadata:
      labels:
        app: arkouda-locale
        name: arkouda-locale
        #annotations:
        #k8s.v1.cni.cncf.io/networks: host-device-conf
    spec:
      nodeSelector:
        locale-host: "true"
      containers:
        - name: arkouda-locale
          image: hokiegeek2/udp-arkouda-server:{{ .Values.releaseVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
          command: [ "sh", "/opt/start-arkouda-locale.sh" ]
          ports:
          - containerPort: 22
            hostPort: 25
          volumeMounts:
          - name: ssh
            mountPath: "/home/ubuntu/ssh-keys"
          env:
            - name: MY_IP
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
            - name: NUM_LOCALES
              value: {{ .Values.server.numLocales | quote }}
            - name: AUTHENTICATE
              value: {{ .Values.server.authenticate | quote }} 
            - name: VERBOSE
              value: {{ .Values.server.verbose | quote }}   
            - name: MEMTRACK
              value: {{ .Values.server.memTrack | quote }}
            - name: CHPL_RT_NUM_THREADS_PER_LOCALE
              value: {{ .Values.server.threadsPerLocale | quote }}         
      volumes:
        - name: ssh
          secret:
            secretName: arkouda-ssh
       
