apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: arkouda-locale
spec:
  replicas: {{ .Values.server.numLocales }}
  selector:
    matchLabels:
      app: arkouda-locale
  template:
    metadata:
      labels:
        app: arkouda-locale
        name: arkouda-locale
    spec:
      containers:
        - name: arkouda-locale
          image: hokiegeek2/udp-arkouda-server:{{ .Values.releaseVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
          command: [ "sh", "/opt/start-arkouda-locale.sh" ]
          lifecycle:
            preStop:
              exec:
                command: ["python3","-c","import os; import arkouda as ak; ak.connect('{}.{}'.format(os.environ['NAMESPACE'],os.environ['EXTERNAL_SERVICE_NAME'])), ak.shutdown()]"]
          ports:
          - containerPort: 22
            hostPort: 25
          volumeMounts:
          - name: ssl
            mountPath: "/etc/ssl/arkouda"
          - name: ssh
            mountPath: "/home/ubuntu/ssh-keys"
          {{- if eq .Values.external.persistence.enabled true }}
          - name: locale
            mountPath: "/opt/locale"
          {{- end }}
          env:
            - name: MY_IP
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
            - name: NUM_LOCALES
              value: {{ .Values.server.numLocales | quote }}
            - name: AUTHENTICATE
              value: {{ .Values.server.authenticate | quote }} 
            - name: VERBOSE
              value: {{ .Values.server.verbose | quote }}   
            - name: MEMTRACK
              value: {{ .Values.server.memTrack | quote }}
            - name: CHPL_RT_NUM_THREADS_PER_LOCALE
              value: {{ .Values.server.threadsPerLocale | quote }} 
            - name: CERT_FILE
              value: {{ .Values.external.certFile | quote }}
            - name: KEY_FILE
              value: {{ .Values.external.keyFile | quote }}
            - name: K8S_HOST
              value: {{ .Values.external.k8sHost | quote }}
            - name: NAMESPACE
              value: {{ .Values.external.namespace }}
            - name: EXTERNAL_SERVICE_NAME
              value: {{ .Values.external.externalServiceName }}        
      volumes:
        - name: ssl
          secret:
            secretName: arkouda-server
        - name: ssh
          secret:
            secretName: arkouda-ssh
        {{- if eq .Values.external.persistence.enabled true }}
        - name: locale
          hostPath:
            path: "/mnt/data/arkouda"
        {{- end }}  
