apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.appName }}
spec:
  replicas: {{ .Values.numServers }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
        name: {{ .Values.deployment.appName }}
    spec:
      containers:
        - name: arkouda-server
          image: hokiegeek2/arkouda-server:{{ .Values.releaseVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
          ports:
          - containerPort: {{ .Values.server.port }}
            hostPort: {{ .Values.server.port }}
          env:
            - name: NUMLOCALES
              value: {{ .Values.server.numLocales | quote}}
            - name: AUTHENTICATE
              value: {{ .Values.server.authenticate | quote}} 
            - name: VERBOSE
              value: {{ .Values.server.verbose | quote}}   
            - name: MEMTRACK
              value: {{ .Values.server.memTrack | quote}}                
