apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.serviceName }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app: {{ .Values.deployment.appName }}
